* Deep Dive Into Modern Web Development (Helsinki University)

** Course Site
[[https://fullstackopen.com/en/]]

** Submission System Site
[[https://studies.cs.helsinki.fi/stats/courses/fullstackopen]]

** Submission instructions
Submitting exercises

The exercises are submitted through GitHub and marked as done on the
"my submissions" tab of the submission application.

If you are submitting exercises from different parts to the same
repository, use an appropriate system for naming your directories.
You can of course create a new repository for each part.
If you are using a private repository, add mluukkai as a collaborator.

Exercises are submitted one part at a time.
You will mark the number of exercises you have
completed from that module.
Once you have submitted exercises for a part, you can no longer
submit any more exercises for that part.

A system for detecting plagiarism is used to check exercises
submitted to GitHub.
If code is found from model answers or multiple students hand
in the same code, the situation is handled according
to the policy on plagiarism of the University of Helsinki.

Many of the exercises build a larger application bit by bit.
In these cases, submitting only the completed application is enough.
You can make a commit after each exercise, but that is not compulsory.

You can submit all of the exercises into the same repository,
or use multiple different repositories.
If you submit exercises from different parts into the
same repository, name your directories well.
If you use a private repository to submit the exercises,
add mluukkai as a collaborator to it.

One good way to name the directories in your
submission repository is as follows:

part0
part1
  courseinfo
  unicafe
  anecdotes
part2
  courseinfo
  phonebook
  countries

So, each part has its own directory, which contains
a directory for each exercise set
(like the unicafe exercises in part 1).

The exercises are submitted one part at a time.
When you have submitted the exercises for a part,
you can no longer submit any missed exercises for that part.
